/**
 * 16 Personalities (IPIP-120) Questions Bank
 *
 * Baseado no IPIP-NEO-120 — Domínio Público
 * Referência: https://ipip.ori.org/newNEODomainsKey.htm
 *
 * - 120 itens Likert 1-5 (1=Discordo Totalmente, 5=Concordo Totalmente)
 * - 24 itens por dimensão Big Five (O, C, E, A, N)
 * - Itens keyed='-' são invertidos: score = 6 - resposta
 */
import { IpipQuestion } from '@/modules/tests/domain/interfaces/ipip-question.interface';

export const IPIP_120_QUESTIONS: IpipQuestion[] = [
  { id: 'ipip-1', itemNumber: 1, text: 'Tenho uma imaginação vívida', dimension: 'O', keyed: '+' },
  { id: 'ipip-2', itemNumber: 2, text: 'Tenho dificuldade em entender ideias abstratas', dimension: 'O', keyed: '-' },
  { id: 'ipip-3', itemNumber: 3, text: 'Gosto de refletir sobre filosofia e questões profundas', dimension: 'O', keyed: '+' },
  { id: 'ipip-4', itemNumber: 4, text: 'Não gosto de arte ou música', dimension: 'O', keyed: '-' },
  { id: 'ipip-5', itemNumber: 5, text: 'Tenho curiosidade sobre muitas coisas diferentes', dimension: 'O', keyed: '+' },
  { id: 'ipip-6', itemNumber: 6, text: 'Prefiro o familiar ao novo e desconhecido', dimension: 'O', keyed: '-' },
  { id: 'ipip-7', itemNumber: 7, text: 'Tenho uma imaginação ativa e criativa', dimension: 'O', keyed: '+' },
  { id: 'ipip-8', itemNumber: 8, text: 'Raramente faço associações entre ideias diferentes', dimension: 'O', keyed: '-' },
  { id: 'ipip-9', itemNumber: 9, text: 'Aprecio experiências de beleza e arte', dimension: 'O', keyed: '+' },
  { id: 'ipip-10', itemNumber: 10, text: 'Não gosto de poesia ou literatura', dimension: 'O', keyed: '-' },
  { id: 'ipip-11', itemNumber: 11, text: 'Gosto de explorar novas ideias e conceitos', dimension: 'O', keyed: '+' },
  { id: 'ipip-12', itemNumber: 12, text: 'Tenho pouco interesse em arte e criatividade', dimension: 'O', keyed: '-' },
  { id: 'ipip-13', itemNumber: 13, text: 'Busco significado profundo nas experiências', dimension: 'O', keyed: '+' },
  { id: 'ipip-14', itemNumber: 14, text: 'Prefiro rotinas a novas situações', dimension: 'O', keyed: '-' },
  { id: 'ipip-15', itemNumber: 15, text: 'Aprecio música, arte e literatura', dimension: 'O', keyed: '+' },
  { id: 'ipip-16', itemNumber: 16, text: 'Não vejo sentido em explorar filosofia', dimension: 'O', keyed: '-' },
  { id: 'ipip-17', itemNumber: 17, text: 'Tenho muita criatividade e originalidade', dimension: 'O', keyed: '+' },
  { id: 'ipip-18', itemNumber: 18, text: 'Não tenho boa imaginação', dimension: 'O', keyed: '-' },
  { id: 'ipip-19', itemNumber: 19, text: 'Gosto de aprender sobre culturas e tradições diferentes', dimension: 'O', keyed: '+' },
  { id: 'ipip-20', itemNumber: 20, text: 'Raramente penso sobre questões filosóficas', dimension: 'O', keyed: '-' },
  { id: 'ipip-21', itemNumber: 21, text: 'Faço conexões criativas entre ideias distantes', dimension: 'O', keyed: '+' },
  { id: 'ipip-22', itemNumber: 22, text: 'Prefiro pensar de forma concreta e prática', dimension: 'O', keyed: '-' },
  { id: 'ipip-23', itemNumber: 23, text: 'Tenho interesse em poesia, arte ou música', dimension: 'O', keyed: '+' },
  { id: 'ipip-24', itemNumber: 24, text: 'Acho que criatividade é supervalorizada', dimension: 'O', keyed: '-' },

  // ── Conscientiousness (C) — 24 itens ─────────────────────────────────────────
  { id: 'ipip-25', itemNumber: 25, text: 'Sou sempre preparado e organizado', dimension: 'C', keyed: '+' },
  { id: 'ipip-26', itemNumber: 26, text: 'Frequentemente esqueço de colocar as coisas de volta no lugar', dimension: 'C', keyed: '-' },
  { id: 'ipip-27', itemNumber: 27, text: 'Cumpro prazos e compromissos com rigor', dimension: 'C', keyed: '+' },
  { id: 'ipip-28', itemNumber: 28, text: 'Frequentemente deixo tarefas incompletas', dimension: 'C', keyed: '-' },
  { id: 'ipip-29', itemNumber: 29, text: 'Sigo um plano e não me desvio facilmente', dimension: 'C', keyed: '+' },
  { id: 'ipip-30', itemNumber: 30, text: 'Tenho dificuldade em manter a organização', dimension: 'C', keyed: '-' },
  { id: 'ipip-31', itemNumber: 31, text: 'Presto atenção aos detalhes no meu trabalho', dimension: 'C', keyed: '+' },
  { id: 'ipip-32', itemNumber: 32, text: 'Faço bagunça e raramente limpei depois', dimension: 'C', keyed: '-' },
  { id: 'ipip-33', itemNumber: 33, text: 'Sempre termino o que começo', dimension: 'C', keyed: '+' },
  { id: 'ipip-34', itemNumber: 34, text: 'Evito responsabilidades quando possível', dimension: 'C', keyed: '-' },
  { id: 'ipip-35', itemNumber: 35, text: 'Trabalho de forma eficiente e sem desperdiçar tempo', dimension: 'C', keyed: '+' },
  { id: 'ipip-36', itemNumber: 36, text: 'Frequentemente perco tempo com distrações', dimension: 'C', keyed: '-' },
  { id: 'ipip-37', itemNumber: 37, text: 'Tenho disciplina para seguir meus planos', dimension: 'C', keyed: '+' },
  { id: 'ipip-38', itemNumber: 38, text: 'Tenho dificuldade em me concentrar em uma tarefa', dimension: 'C', keyed: '-' },
  { id: 'ipip-39', itemNumber: 39, text: 'Sou confiável e responsável', dimension: 'C', keyed: '+' },
  { id: 'ipip-40', itemNumber: 40, text: 'Frequentemente chego atrasado', dimension: 'C', keyed: '-' },
  { id: 'ipip-41', itemNumber: 41, text: 'Estabeleço objetivos claros e trabalho para alcançá-los', dimension: 'C', keyed: '+' },
  { id: 'ipip-42', itemNumber: 42, text: 'Raramente me preparo adequadamente para eventos importantes', dimension: 'C', keyed: '-' },
  { id: 'ipip-43', itemNumber: 43, text: 'Sou cuidadoso e preciso no que faço', dimension: 'C', keyed: '+' },
  { id: 'ipip-44', itemNumber: 44, text: 'Tenho dificuldade em resistir a tentações', dimension: 'C', keyed: '-' },
  { id: 'ipip-45', itemNumber: 45, text: 'Planejo meu futuro com cuidado', dimension: 'C', keyed: '+' },
  { id: 'ipip-46', itemNumber: 46, text: 'Frequentemente ajo sem pensar nas consequências', dimension: 'C', keyed: '-' },
  { id: 'ipip-47', itemNumber: 47, text: 'Tenho altos padrões de desempenho para mim mesmo', dimension: 'C', keyed: '+' },
  { id: 'ipip-48', itemNumber: 48, text: 'Me deixo levar facilmente e perco o foco', dimension: 'C', keyed: '-' },

  // ── Extraversion (E) — 24 itens ───────────────────────────────────────────────
  { id: 'ipip-49', itemNumber: 49, text: 'Sinto-me confortável sendo o centro das atenções', dimension: 'E', keyed: '+' },
  { id: 'ipip-50', itemNumber: 50, text: 'Prefiro ficar em segundo plano', dimension: 'E', keyed: '-' },
  { id: 'ipip-51', itemNumber: 51, text: 'Gosto de conversar com muitas pessoas diferentes', dimension: 'E', keyed: '+' },
  { id: 'ipip-52', itemNumber: 52, text: 'Prefiro ficar em casa a sair e socializar', dimension: 'E', keyed: '-' },
  { id: 'ipip-53', itemNumber: 53, text: 'Faço amizades com facilidade', dimension: 'E', keyed: '+' },
  { id: 'ipip-54', itemNumber: 54, text: 'Raramente falo com estranhos', dimension: 'E', keyed: '-' },
  { id: 'ipip-55', itemNumber: 55, text: 'Sinto-me animado em festas e eventos sociais', dimension: 'E', keyed: '+' },
  { id: 'ipip-56', itemNumber: 56, text: 'Me sinto desconfortável sendo o foco de atenção', dimension: 'E', keyed: '-' },
  { id: 'ipip-57', itemNumber: 57, text: 'Começo conversas com facilidade', dimension: 'E', keyed: '+' },
  { id: 'ipip-58', itemNumber: 58, text: 'Tenho poucos amigos próximos', dimension: 'E', keyed: '-' },
  { id: 'ipip-59', itemNumber: 59, text: 'Me energizo ao estar com outras pessoas', dimension: 'E', keyed: '+' },
  { id: 'ipip-60', itemNumber: 60, text: 'Prefiro ambientes tranquilos e solitários', dimension: 'E', keyed: '-' },
  { id: 'ipip-61', itemNumber: 61, text: 'Adoro festas e reuniões sociais', dimension: 'E', keyed: '+' },
  { id: 'ipip-62', itemNumber: 62, text: 'Acho difícil conversar com pessoas que não conheço', dimension: 'E', keyed: '-' },
  { id: 'ipip-63', itemNumber: 63, text: 'Falo muito e com entusiasmo', dimension: 'E', keyed: '+' },
  { id: 'ipip-64', itemNumber: 64, text: 'Me sinto drenado depois de interações sociais longas', dimension: 'E', keyed: '-' },
  { id: 'ipip-65', itemNumber: 65, text: 'Gosto de liderar grupos e equipes', dimension: 'E', keyed: '+' },
  { id: 'ipip-66', itemNumber: 66, text: 'Prefiro trabalhar sozinho', dimension: 'E', keyed: '-' },
  { id: 'ipip-67', itemNumber: 67, text: 'Me sinto à vontade em ambientes movimentados', dimension: 'E', keyed: '+' },
  { id: 'ipip-68', itemNumber: 68, text: 'Evito situações sociais quando possível', dimension: 'E', keyed: '-' },
  { id: 'ipip-69', itemNumber: 69, text: 'Tenho presença marcante em grupos', dimension: 'E', keyed: '+' },
  { id: 'ipip-70', itemNumber: 70, text: 'Me sinto mais confortável em ambientes pequenos', dimension: 'E', keyed: '-' },
  { id: 'ipip-71', itemNumber: 71, text: 'Gosto de conhecer novas pessoas constantemente', dimension: 'E', keyed: '+' },
  { id: 'ipip-72', itemNumber: 72, text: 'Fico esgotado com interações sociais intensas', dimension: 'E', keyed: '-' },

  // ── Agreeableness (A) — 24 itens ─────────────────────────────────────────────
  { id: 'ipip-73', itemNumber: 73, text: 'Me preocupo com os outros e com seu bem-estar', dimension: 'A', keyed: '+' },
  { id: 'ipip-74', itemNumber: 74, text: 'Raramente me preocupo com problemas alheios', dimension: 'A', keyed: '-' },
  { id: 'ipip-75', itemNumber: 75, text: 'Acredito que as pessoas têm boas intenções', dimension: 'A', keyed: '+' },
  { id: 'ipip-76', itemNumber: 76, text: 'Desconfio das motivações das pessoas', dimension: 'A', keyed: '-' },
  { id: 'ipip-77', itemNumber: 77, text: 'Gosto de cooperar e trabalhar em equipe', dimension: 'A', keyed: '+' },
  { id: 'ipip-78', itemNumber: 78, text: 'Prefiro competir a cooperar', dimension: 'A', keyed: '-' },
  { id: 'ipip-79', itemNumber: 79, text: 'Sou gentil e bondoso com as pessoas ao meu redor', dimension: 'A', keyed: '+' },
  { id: 'ipip-80', itemNumber: 80, text: 'Frequentemente critico ou julgo os outros', dimension: 'A', keyed: '-' },
  { id: 'ipip-81', itemNumber: 81, text: 'Me emociono facilmente com situações dos outros', dimension: 'A', keyed: '+' },
  { id: 'ipip-82', itemNumber: 82, text: 'Raramente sinto empatia pelos outros', dimension: 'A', keyed: '-' },
  { id: 'ipip-83', itemNumber: 83, text: 'Faço esforço para ajudar as pessoas ao meu redor', dimension: 'A', keyed: '+' },
  { id: 'ipip-84', itemNumber: 84, text: 'Coloco meus interesses acima dos outros', dimension: 'A', keyed: '-' },
  { id: 'ipip-85', itemNumber: 85, text: 'Sou caloroso e acolhedor com novas pessoas', dimension: 'A', keyed: '+' },
  { id: 'ipip-86', itemNumber: 86, text: 'Tenho dificuldade em confiar nas pessoas', dimension: 'A', keyed: '-' },
  { id: 'ipip-87', itemNumber: 87, text: 'Perdoo com facilidade quando alguém me magoa', dimension: 'A', keyed: '+' },
  { id: 'ipip-88', itemNumber: 88, text: 'Guardo rancor por muito tempo', dimension: 'A', keyed: '-' },
  { id: 'ipip-89', itemNumber: 89, text: 'Sinto compaixão pelos menos afortunados', dimension: 'A', keyed: '+' },
  { id: 'ipip-90', itemNumber: 90, text: 'Me importo pouco com os problemas dos outros', dimension: 'A', keyed: '-' },
  { id: 'ipip-91', itemNumber: 91, text: 'Gosto de fazer as pessoas se sentirem bem', dimension: 'A', keyed: '+' },
  { id: 'ipip-92', itemNumber: 92, text: 'Frequentemente discuto com as pessoas', dimension: 'A', keyed: '-' },
  { id: 'ipip-93', itemNumber: 93, text: 'Tenho boa vontade para com todos', dimension: 'A', keyed: '+' },
  { id: 'ipip-94', itemNumber: 94, text: 'Sou frio e distante com as pessoas', dimension: 'A', keyed: '-' },
  { id: 'ipip-95', itemNumber: 95, text: 'Considero o impacto das minhas ações sobre os outros', dimension: 'A', keyed: '+' },
  { id: 'ipip-96', itemNumber: 96, text: 'Muitas vezes insulto ou deprecio os outros', dimension: 'A', keyed: '-' },

  // ── Neuroticism (N) — 24 itens ────────────────────────────────────────────────
  { id: 'ipip-97', itemNumber: 97, text: 'Me estresso facilmente com situações do dia a dia', dimension: 'N', keyed: '+' },
  { id: 'ipip-98', itemNumber: 98, text: 'Raramente me sinto ansioso ou preocupado', dimension: 'N', keyed: '-' },
  { id: 'ipip-99', itemNumber: 99, text: 'Fico irritado com frequência', dimension: 'N', keyed: '+' },
  { id: 'ipip-100', itemNumber: 100, text: 'Mantenho a calma mesmo em situações difíceis', dimension: 'N', keyed: '-' },
  { id: 'ipip-101', itemNumber: 101, text: 'Me preocupo com muitas coisas ao mesmo tempo', dimension: 'N', keyed: '+' },
  { id: 'ipip-102', itemNumber: 102, text: 'Raramente fico deprimido', dimension: 'N', keyed: '-' },
  { id: 'ipip-103', itemNumber: 103, text: 'Tenho oscilações de humor frequentes', dimension: 'N', keyed: '+' },
  { id: 'ipip-104', itemNumber: 104, text: 'Me sinto confortável comigo mesmo na maioria das vezes', dimension: 'N', keyed: '-' },
  { id: 'ipip-105', itemNumber: 105, text: 'Frequentemente me sinto ansioso ou tenso', dimension: 'N', keyed: '+' },
  { id: 'ipip-106', itemNumber: 106, text: 'Sou emocionalmente estável e equilibrado', dimension: 'N', keyed: '-' },
  { id: 'ipip-107', itemNumber: 107, text: 'Me preocupo excessivamente com o que pode dar errado', dimension: 'N', keyed: '+' },
  { id: 'ipip-108', itemNumber: 108, text: 'Lido bem com situações de pressão e estresse', dimension: 'N', keyed: '-' },
  { id: 'ipip-109', itemNumber: 109, text: 'Às vezes me sinto sem esperança em relação ao futuro', dimension: 'N', keyed: '+' },
  { id: 'ipip-110', itemNumber: 110, text: 'Raramente me sinto triste ou deprimido', dimension: 'N', keyed: '-' },
  { id: 'ipip-111', itemNumber: 111, text: 'Me sinto sobrecarregado com frequência', dimension: 'N', keyed: '+' },
  { id: 'ipip-112', itemNumber: 112, text: 'Tenho alta resistência emocional', dimension: 'N', keyed: '-' },
  { id: 'ipip-113', itemNumber: 113, text: 'Fico frustrado com facilidade quando as coisas não saem como esperado', dimension: 'N', keyed: '+' },
  { id: 'ipip-114', itemNumber: 114, text: 'Me recupero rapidamente de situações difíceis', dimension: 'N', keyed: '-' },
  { id: 'ipip-115', itemNumber: 115, text: 'Sinto-me inseguro em situações novas ou desconhecidas', dimension: 'N', keyed: '+' },
  { id: 'ipip-116', itemNumber: 116, text: 'Confio em mim mesmo na maior parte do tempo', dimension: 'N', keyed: '-' },
  { id: 'ipip-117', itemNumber: 117, text: 'Tenho dificuldade em controlar minhas preocupações', dimension: 'N', keyed: '+' },
  { id: 'ipip-118', itemNumber: 118, text: 'Não me deixo abalar por críticas', dimension: 'N', keyed: '-' },
  { id: 'ipip-119', itemNumber: 119, text: 'Frequentemente sinto que algo ruim vai acontecer', dimension: 'N', keyed: '+' },
  { id: 'ipip-120', itemNumber: 120, text: 'Tenho uma perspectiva geralmente positiva e tranquila', dimension: 'N', keyed: '-' },
];
